### ISSUE TITLE
Error when executing train_naturallanguage_rm.sh

### ISSUE THREAD

**Issue by chengzelei** [vaskarnathscale/goal-conditioned-rm#1]
Thank you for your impressive work! When I follow the instruction to train a reward model over hh-rlhf dataset with the following shell script:

# llama7b contrastive RM training
set -x 

# Do training
read -r -d '' training_commands <<EOF
./examples/train_rm.py \    
     --logging_steps 1 \
     --eval_steps 1000 \
     --train_batch_size 64 \
     --micro_train_batch_size 1 \
     --pretrain meta-llama/Meta-Llama-3-8B-Instruct \
     --bf16 \
     --max_epochs 1 \
     --max_len 4096 \
     --zero_stage 3 \
     --learning_rate 1e-5 \
     --dataset Anthropic/hh-rlhf \
     --dataset_probs 1 \
     --contrastive_loss \
     --contrastive_loss_beta 5e-1\
     --unsim_samples 16 \
     --flash_attn \
     --gradient_checkpointing \
     --seed 0 \
     --reward_model_strategy contrastive \
     --contrastive_strategy cosine \
     --value_head_strategy linear \
     --source_state_percentile 0 \
     --goal_state_percentile 0
EOF

if [[ ${1} != "slurm" ]]; then
     deepspeed $training_commands
fi

the program raises an error:

usage: train_rm.py [-h] [--pretrain PRETRAIN] [--dataset DATASET] [--dataset_probs DATASET_PROBS] [--save_path SAVE_PATH] [--save_steps SAVE_STEPS]
                   [--logging_steps LOGGING_STEPS] [--eval_steps EVAL_STEPS] [--ckpt_path CKPT_PATH] [--max_ckpt_num MAX_CKPT_NUM]
                   [--max_ckpt_mem MAX_CKPT_MEM] [--max_epochs MAX_EPOCHS] [--micro_train_batch_size MICRO_TRAIN_BATCH_SIZE]
                   [--train_batch_size TRAIN_BATCH_SIZE] [--max_samples MAX_SAMPLES] [--load_checkpoint] [--max_norm MAX_NORM] [--max_len MAX_LEN] [--l2 L2]
                   [--loss LOSS] [--gradient_checkpointing] [--seed SEED] [--local_rank LOCAL_RANK] [--zero_stage ZERO_STAGE] [--bf16]
                   [--learning_rate LEARNING_RATE] [--zpg ZPG] [--adam_offload] [--flash_attn] [--compute_fp32_loss] [--margin_loss]
                   [--aux_loss_coef AUX_LOSS_COEF] [--grad_accum_dtype GRAD_ACCUM_DTYPE] [--disable_trace_cache] [--load_in_4bit] [--lora_rank LORA_RANK]
                   [--lora_alpha LORA_ALPHA] [--target_modules TARGET_MODULES] [--input_template INPUT_TEMPLATE] [--gradient_checkpointing_use_reentrant]
                   [--contrastive_loss_beta CONTRASTIVE_LOSS_BETA] [--unsim_samples UNSIM_SAMPLES] [--sim_samples SIM_SAMPLES] --reward_model_strategy
                   REWARD_MODEL_STRATEGY --contrastive_strategy CONTRASTIVE_STRATEGY --value_head_strategy VALUE_HEAD_STRATEGY
                   [--source_state_percentile SOURCE_STATE_PERCENTILE] [--goal_state_percentile GOAL_STATE_PERCENTILE] [--bos_token BOS_TOKEN]
                   [--eos_token EOS_TOKEN] [--pad_token PAD_TOKEN] [--unk_token UNK_TOKEN] [--prompt_key PROMPT_KEY] [--chosen_key CHOSEN_KEY]
                   [--rejected_key REJECTED_KEY] [--apply_chat_template] [--use_wandb USE_WANDB] [--wandb_org WANDB_ORG] [--wandb_group WANDB_GROUP]
                   [--wandb_project WANDB_PROJECT] [--wandb_run_name WANDB_RUN_NAME]
train_rm.py: error: argument --contrastive_loss_beta: expected one argument

May I ask if you have encountered similar problems before? Any insights would be appreciated.

**Comment by vaskarnathscale** [comment]
Hi Zelei, 

Thanks for raising the issue! I believe you need to specify the contrastive_loss_beta as a float value (e.g. 0.5) or maybe wrap 5e-1 in quotations. Let me know if this works, I am also going to try and reproduce this

**Comment by chengzelei** [comment]
I tried to use 0.5 initially but failed. Later, I made an attempt to write 0.5 as 5e-1. It also didn't work..

**Comment by vaskarnathscale** [comment]
Ah! thanks for flagging this. looks like `--contrastive_loss` was a parameter in a previous version of the code and no longer exists. I updated the run [script](https://github.com/vaskarnathscale/goal-conditioned-rm/blob/08739fd730a199f75cd9a0e57c7f9c391a1c9432/examples/run_scripts/train_naturallanguage_rm.sh#L22C1-L25C36). I remove the outdated flag and added 3 additional inputs that specify the same thing:

```
     --reward_model_strategy contrastive \
     --contrastive_strategy cosine \
     --value_head_strategy linear \
```

and so the run script now looks like:

```
read -r -d '' training_commands <<EOF
./examples/train_rm.py \
     --logging_steps 1 \
     --eval_steps 1000 \
     --train_batch_size 64 \
     --micro_train_batch_size 1 \
     --pretrain meta-llama/Meta-Llama-3-8B-Instruct \
     --bf16 \
     --max_epochs 1 \
     --max_len 4096 \
     --zero_stage 3 \
     --learning_rate 0.1 \
     --dataset ./hh-rlhf \
     --dataset_probs 1.0 \
     --contrastive_loss_beta 0.5 \
     --reward_model_strategy contrastive \
     --contrastive_strategy cosine \
     --value_head_strategy linear \
     --unsim_samples 16 \
     --flash_attn \
     --gradient_checkpointing \
     --save_path helpful-harmless-llama-3-8b-rm 
EOF
```

**Comment by chengzelei** [comment]
Hi, I tried the new script. However, an error occured regarding loss.py in openrlhf.

[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/zck7060/goal-conditioned-rm/./examples/train_rm.py", line 214, in <module>
[rank1]:     train(args)
[rank1]:   File "/home/zck7060/goal-conditioned-rm/./examples/train_rm.py", line 131, in train
[rank1]:     trainer.fit(args)
[rank1]:   File "/home/zck7060/goal-conditioned-rm/openrlhf/trainer/rm_trainer.py", line 153, in fit
[rank1]:     contrastive_loss = self.contrastive_loss(chosen_lh, rejected_lh, cna, rna)
[rank1]:   File "/home/zck7060/miniconda3/envs/openrlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/zck7060/miniconda3/envs/openrlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/zck7060/goal-conditioned-rm/openrlhf/models/loss.py", line 59, in forward
[rank1]:     ((source_state_percentile * chosen_na.unsqueeze(1)) + 1).floor().int()
[rank1]: UnboundLocalError: local variable 'source_state_percentile' referenced before assignment

I checked the specific lines of code in loss.py. I found that if self.source_state_percetile is None, the error should occur. May I ask how to solve this problem? Thanks

Here is the related code in loss.py:

        if self.source_state_percentile is not None:
            source_state_percentile = (self.source_state_percentile - 1) * random_values[:, 0] + 1
        if self.goal_state_percentile is not None:
            goal_state_percentile = (self.goal_state_percentile - 1) * random_values[:, 1] + 1

        source_state_sampled_values = (
            ((source_state_percentile * chosen_na.unsqueeze(1)) + 1).floor().int()
